export const ADD_BOOK = 'ADD_BOOK';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const LOAD_BOOKS_START = 'LOAD_BOOKS_START';
export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
